# Form implementation generated from reading ui file 'tambahpenjahit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(490, 285)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(130, 30, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 130, 111, 16))
        self.label_2.setObjectName("label_2")
        self.tambahNamaPenjahit = QtWidgets.QLineEdit(parent=Dialog)
        self.tambahNamaPenjahit.setGeometry(QtCore.QRect(210, 130, 201, 21))
        self.tambahNamaPenjahit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 180, 111, 16))
        self.label_4.setObjectName("label_4")
        self.tambahTelpPenjahit = QtWidgets.QLineEdit(parent=Dialog)
        self.tambahTelpPenjahit.setGeometry(QtCore.QRect(210, 180, 201, 21))
        self.tambahTelpPenjahit.setObjectName("lineEdit_2")
        self.tambahPenjahitBtn = QtWidgets.QPushButton(parent=Dialog)
        self.tambahPenjahitBtn.setGeometry(QtCore.QRect(337, 210, 75, 24))
        self.tambahPenjahitBtn.setObjectName("tambahPenjahitBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Tambah Penjahit"))
        self.label_2.setText(_translate("Dialog", "Nama Penjahit"))
        self.label_4.setText(_translate("Dialog", "Nomor Telepon"))
        self.tambahPenjahitBtn.setText(_translate("Dialog", "Simpan"))
